spring.application.name=breakdown-dashboard-svc
# Enable debug mode for more detailed Spring Boot startup logs
debug=true

# Set global logging level for your application (e.g., com.nihith)
logging.level.com.nihith=DEBUG
logging.level.com.nihith.calculationengine.settlements=DEBUG

# Set logging levels for specific Spring components (optional)
logging.level.org.springframework.web=DEBUG
logging.level.org.hibernate=INFO